
services:
  app:
    build:
      context: .  # Текущая директория, где находится docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Замените на нужные порты
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=Deviliry;Username=postgres;Password=1407"
    depends_on:
      - db

  db:
    image: postgres:16  # Образ базы данных
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1407
      POSTGRES_DB: Deviliry
    volumes:
      - ./Database:/var/lib/postgresql/data  # Привязка к локальной директории для хранения данных
    ports:
      - "5432:5432"